db:
  host: "postgresql"
  user: "testFlask"
  password: "testFlask"
  database: "testFlask"
  port: "5432"
  cursorSize: 100
keycloak:
  baseurl: "http://localhost:5001/"
  realm: "test-service"
  secretKey: "t6174ElRusm8kI0xggunVSbLcrpE0dnu"
  user: "admin"
  password: "admin"



