db:
  host: DB_HOST
  user: DB_USER
  password: DB_PASSWORD
  database: DB_NAME
  port: DB_PORT
  cursorSize: 100
keycloak:
  baseurl: KEYCLOAKURL
  realm: REALM_NAME
  secretKey: SECRET_KEY
  user: USERNAME
  password: PASSWORD



